# These values shouldn't be set here because it will be packaged in the .jar file. Instead, opt for
# setting them as environmental variables in /etc/environment on the thermostat device itself. Use the
# same environment variable names below; ENDPOINT, DEVICE_ID, DEVICE_SECRET.
api.rootAddress=${ENDPOINT:}
api.deviceId=${DEVICE_ID:}
api.deviceSecret=${DEVICE_SECRET:}